--- 
run_list: 
- tvdinner
tvd: 
  class: Vagrant
  name: vagrant
  author: Tom Bombadil
  email: amanibhavam@destructuring.org
  summary: vagrant cookbook and utilities
  description: vagrant cookbook and utilities
  homepage: http://destructuring.org/tvd-vagrant
  git_url: https://github.com/destructuring/tvd-vagrant
